[private]
default:
    @just --list

configure:
  cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build

build:
  cmake --build build

unlimited: build
  ./build/mpcalc 1

limited: build
  ./build/mpcalc 2

sample: build
  time ./build/mpcalc 3

valgrind_complex: build
  valgrind --leak-check=fsize_t ./build/mpcalc
  # valgrind --leak-check=fsize_t ./build/drawing inputs/complex.in inputs/complex.pgm 160x160

clean:
  rm -rf build
